name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  schedule:
    - cron: "0 0 * * 0"   # retrain every Sunday

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run tests
      run: pytest tests/

    - name: Train model
      run: python train.py

    - name: Build Docker image
      run: docker build -t ghcr.io/${{ github.repository }}/stock-mlops-app:latest .

    - name: Push Docker image
      run: |
        echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
        docker push ghcr.io/${{ github.repository }}/stock-mlops-app:latest
